# Docker Build
# gcloud builds submit --config=cloudbuild.yaml .
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 
         '${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE}:${_VERSION}', '.']
images:
- '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}'
substitutions:
  _LOCATION: 'europe-west1'
  _REPOSITORY: 'datahem-runner'
  _IMAGE: 'fast-api'
  _VERSION: 'latest'
